### PR TITLE
Unify and document community contributions for notification methods

### PR DESCRIPTION
**Pull request by matomatical**

### CODE REVIEW

**Comment by matomatical** [comment]
@blueset, @CaviarChen, @josephsurin, thanks so much for your contributions of additional notification methods. I've attempted to unify and document your added notification methods in this PR. Of course, I have probably broken at least one of them, and I don't have the required accounts set up to test them. Is there any chance you could test your preferred notification methods for me by attempting to follow the  instructions in the README, and letting me know if they still work? No rush, I figure this project won't be needed until roughly 5 months from now when semester 2 results are going to be released! Thanks again :)

**Comment by matomatical** [comment]
@blueset, @CaviarChen, @josephsurin, 'tis the season to be WAM-spamming! If you get a chance, please check out this new unified multi-notification-methods version of WAM spammer, and let me know if you find any bugs. I'm unable to test the different methods without accounts for the various services. Thanks for your contribution!

**Comment by CaviarChen** [comment]
I've tested by_wechat and by_push. Both methods work pretty well.

**Comment by blueset** [comment]
I‘d love to give some of these methods a test, but I no longer have any subject to test them with 😅 .

**Comment by matomatical** [comment]
> I‘d love to give some of these methods a test, but I no longer have any subject to test them with  .

Well, congratulations are in order :) but I think it should be enough to configure the methods and spin up the sript once, ~with your unimelb credentials, which probably still work~. The initial message that the script sends to say hello will be an adequate test that I have correctly plugged in your code. Edit: this will work even without unimelb credentials (just type nonsense in at the prompt, or comment out these configuration lines).

Do you think you'd be able to do that?

**Comment by blueset** [comment]
Just tried with the welcome prompt on Telegram & IFTTT webhook, everything is working as expected.

Just another note, would it be better to move token configs of `telegram`, `push`, `ifttt` and `wechat` to arguments of constructors instead of asking from STDIN every time?

**Comment by matomatical** [comment]
> Just tried with the welcome prompt on Telegram & IFTTT webhook, everything is working as expected.

Thanks for the test run.

> would it be better to move token configs of `telegram`, `push`, `ifttt` and `wechat` to arguments of constructors instead of asking from STDIN every time?

Six months ago I asked myself that same question but was not sure of the answer. Now, looking back, it is clear that it's nicer to have the configuration all at the top of the main script. I'll add some constructor arguments and merge it!

Thanks all!

**Pull request merged**
