### PR TITLE
Requests

### PR DESCRIPTION
**Pull request by matomatical**
Ditch selenium in favour of requests and bs4. This addresses both issues #2 and #3.

### CODE REVIEW

**Comment by matomatical** [comment]
Hey @blueset, if you get a chance, could you please take a look and see if I'm roughly doing this right?

Hey @noneuclideangirl, could you please see if this runs on your pi?

**Comment by eleanor-em** [comment]
Seems to work so far!

**Comment by matomatical** [comment]
@blueset I'm going to merge this now, but I'd still appreciate your thoughts on the code when and if you ever get a chance :)

**Comment by blueset** [comment]
LGTM!

**Pull request merged**
