### PR TITLE
Allow for multiple notification methods + Added desktop notifications and log file options

### PR DESCRIPTION
**Pull request by josephsurin**
This is a fork of @blueset\'s fork (#9) of @CaviarChen\'s fork (#7) with the more modular notification interface.

Changes:
- Let the user select multiple notification methods.
- Support for desktop notifications (using [notify2](https://pypi.org/project/notify2/)) (tested on Arch Linux with libnotify)
- Support for a log file notification helper (simply write the email contents to a file, timestamped) (as an alternative for redirecting stdout and stderr to a file for people who don't want to hardcode creds and options)
- Removed the pushbullet dependency from `requirements.txt` and added instructions in the README for it. It still works, just that it is imported only if the user selects it as a notification metod so the program can run without crashing while also not importing or requiring it if unused.

### CODE REVIEW

**Comment by CaviarChen** [comment]
As for removing the pushbullet dependency, maybe what we can do is using pushbullet's HTTP API instead of the pacakge?

**Comment by matomatical** [comment]
Nice! If you don't mind, I'll incorporate this along with some other users' contributions into a new, unified 'notify' submodule.

**Comment by matomatical** [comment]
oops, that wasn't meant to go into master!

**Comment by matomatical** [comment]
That was awkward! I reverted the merge with #11 and then put it in the right place with #12.

**Pull request merged**
